### ISSUE TITLE
Add calendar / track user progress page

### ISSUE THREAD

**Issue by daiHash** [ice-cream-the-fat-cat/my-niwa-frontend#191]
- [ ] Add graph / chart where you can choose a day and it completed tasks
- [ ] Think about how to show the progress
- [ ] Weekly range

**Comment by kome12** [comment]
Just testing around but...
Total in Bar / Line chart
<img width="1148" alt="スクリーンショット 2021-09-12 11 30 23" src="https://user-images.githubusercontent.com/770480/133097068-b089fc56-e9dc-41a1-8f50-dbcea01ee6c7.png">

<img width="1160" alt="スクリーンショット 2021-09-13 16 25 04" src="https://user-images.githubusercontent.com/770480/133097032-fe4a6a0d-0705-4dc3-9e66-27072745e51a.png">


Table format to show more detailed results
<img width="1158" alt="スクリーンショット 2021-09-12 11 30 09" src="https://user-images.githubusercontent.com/770480/133097078-ac29bdcf-6646-4adc-a7e1-286a646880c3.png">

**Comment by kome12** [comment]
Tested a heat map version.
<img width="893" alt="スクリーンショット 2021-09-14 17 06 18" src="https://user-images.githubusercontent.com/770480/133220250-78d0555a-729a-4826-aa27-fc801f4b6b93.png">
