### ISSUE TITLE
CORS issue when accessing GardenView from MyGarden

### ISSUE THREAD

**Issue by kome12** [ice-cream-the-fat-cat/my-niwa-frontend#38]
How to replicate:
1. Access the "My Garden" page
2. Click on a garden to move to the "Garden View"
3. Click on the back button to go back to the "My Garden"

<img width="1596" alt="スクリーンショット 2021-08-28 2 00 22" src="https://user-images.githubusercontent.com/770480/131163017-b4b0bc33-fe87-4b93-b0cf-eb23a3d26aff.png">

<img width="505" alt="スクリーンショット 2021-08-28 2 00 17" src="https://user-images.githubusercontent.com/770480/131163025-316a0b67-f18f-4780-906a-aabde7f8274c.png">

**Comment by daiHash** [comment]
Seems like now its fine. reopen it if getting a CORS issue again
