### ISSUE TITLE
Add interface for CreateRule

### ISSUE THREAD

**Issue by kome12** [ice-cream-the-fat-cat/my-niwa-frontend#50]
Current the Rule interface has _id as optional but we should probably have another interface for CreateRule where _id field is not avaialbe.

**Comment by daiHash** [comment]
Implementing it here
https://github.com/ice-cream-the-fat-cat/my-niwa-frontend/pull/134/files#diff-a21f5b24b7be2cea663b85e27a9a319bde8fa5eb66e77e25ab9bdf753326343eR4
